### ISSUE TITLE
Difference between github version and play store version?

### ISSUE THREAD

**Issue by uaevuon** [Notsfsssf/pixez-flutter#291]
Is there any difference between them?

Like R18 features or something like that.

**Comment by Notsfsssf** [comment]
github版包含一些对于google play不合适的内容，比如彩蛋和捐赠信息，其他地方是一样的。
应用因为分级原因被下架过一次，所以包名不一样。
R18内容是需要自行去官网开启的，和app无关
The github version contains some content that is inappropriate for google play, such as easter eggs and donation information, other places are the same
The app has been removed once due to grading, so the package name is different
R18 content needs to be opened on the official website by itself, and has nothing to do with the app
