### ISSUE TITLE
Twitter link on user page not displayed

### ISSUE THREAD

**Issue by tesmite** [Notsfsssf/pixez-flutter#680]
Even if the user has set a link to their Twitter (currently X) account in the user info, it will not be displayed.
It doesn't seem to be displayed even on the official pixiv app, so pixiv may be preventing it from being displayed in anything other than the browser.
I would appreciate it if you could help us.

**Comment by Notsfsssf** [comment]
很抱歉我对此无能无力，这是因为官方限制了移动端的功能，我只能选择去抓取 web 端的内容，但是 web 端内容一些作品会需要登录，此时就需要另外维护一套身份验证逻辑，这样使用成本极高，且开发成本也极高    

I'm sorry that I can't do anything about this. This is because the official restrictions on the functions of the mobile terminal, I can only choose to capture the content of the web side, but some works of web side content will require login, and at this time, another set of authentication logic needs to be maintained. , so the cost of use is extremely high, and the cost of development is also extremely high

**Comment by tesmite** [comment]
I understand. Thank you very much.
I hope the pixiv secretariat will fix this inconvenient specification.
